name: Sync Fork

on:
  schedule:
    - cron: '15 */4 * * *' # every hour 
  workflow_dispatch: # on button click

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    steps:
      - name: Sync the fork 
        uses: opentffoundation/scripts/.github/workflows/sync.yml@main
        secrets: inherit
