name: YAML Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - "**/*.yml"
      - ".yamllint"
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          format: github
        env:
          LANG: C.UTF-8
